import type { Project } from './types';

/**
 * 全部项目，按时间倒序排列（正在开发的放最前）。
 * 媒体文件放在 `public/media/<slug>/`，路径从站点根写起。
 */
export const projects: Project[] = [
  {
    slug: 'jiugong',
    title: '九宫地下城',
    year: '2026',
    kind: 'indie',
    status: 'in-dev',
    role: '程序',
    team: '两人（我 + 一位策划）',
    tagline: '把肉鸽和卡牌战斗压进一张 3×3 的九宫格里，一层一层往下打。',
    description: [
      '正在和一位策划朋友合作开发的第一款计划上架 Steam 的独立游戏。轻度肉鸽加卡牌战斗：每个房间是一张九宫格，怪物与道具都是牌面，玩家站在中央，用手牌解决周围的一切。',
      '此前 jam 里踩过的坑在这里都换成了更克制的规则和更清晰的信息层级。目前处于抓紧赶工的阶段。',
    ],
    cover: {
      kind: 'video',
      src: '/media/jiugong/loop.mp4',
      poster: '/media/jiugong/poster.webp',
      alt: '九宫地下城战斗画面：九宫格里的怪物牌与角色牌',
    },
    gallery: [
      { kind: 'image', src: '/media/jiugong/shot-2.webp', alt: '岩层 · 藏骨堂 战斗房间' },
      { kind: 'image', src: '/media/jiugong/shot-3.webp', alt: '密林 · 翡翠迷雾 房间信息卡' },
      { kind: 'image', src: '/media/jiugong/shot-1.webp', alt: '九宫地下城标题画面' },
    ],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1YeirBakXw-hCa9dLt81yHg?pwd=g2sw', code: 'g2sw', label: '试玩包' },
    ],
    tags: ['Unity', 'C#', '像素'],
    featured: true,
  },
  {
    slug: 'wind-will-read',
    title: 'Wind Will Read',
    latinTitle: 'Wind Will Read',
    year: '2025',
    kind: 'jam',
    status: 'shipped',
    event: 'thatgamecompany × COREBLAZER Game Jam 2025',
    award: '最佳视觉设计 第一名（267 部参赛作品）',
    role: '美术之外的一切：程序、关卡、叙事系统',
    team: '两人（我 + 美术 Ruby），一位动画朋友帮忙',
    tagline: '你是末世小镇里的机器人邮递员。追着每一封信走，把留下来的人重新连起来。',
    description: [
      '一款叙事探索游戏。小镇已经被雪和时间掩埋，你没有答案，只有信。通过追踪每封信的轨迹，你默默软化了留下的人们的心，重燃破碎社区的温暖。',
      '基本上是我和美术 Ruby 两个人做完的，我负责除了美术之外的所有部分。中途走掉了一位策划，但游戏还是按时交上了，并在 267 部作品里拿到了最佳视觉设计第一名，后来也被带到线下展会给玩家试玩。',
    ],
    cover: {
      kind: 'video',
      src: '/media/wind-will-read/loop.mp4',
      poster: '/media/wind-will-read/poster.webp',
      alt: 'Wind Will Read：雪中的小镇，机器人邮递员走在屋顶上',
    },
    gallery: [
      {
        kind: 'video',
        src: '/media/wind-will-read/loop-2.mp4',
        poster: '/media/wind-will-read/poster.webp',
        alt: 'Wind Will Read：邮局内部分拣信件',
      },
      { kind: 'image', src: '/media/wind-will-read/expo.webp', alt: '线下展会上玩家试玩 Wind Will Read' },
      { kind: 'image', src: '/media/wind-will-read/award.webp', alt: 'itch.io 结果页：Best Visual Design 第一名' },
    ],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1UZfoczs9Pn-XWkvDI2mCzQ?pwd=9c26', code: '9c26', label: '试玩包' },
      { kind: 'video', url: 'https://www.bilibili.com/video/BV1ZDguzvEd7/', label: '演示视频 · B站' },
    ],
    tags: ['Unity', 'C#', '叙事'],
    featured: true,
  },
  {
    slug: 'phantom-flash',
    title: 'PhantomFlash',
    latinTitle: 'PhantomFlash',
    year: '2025',
    kind: 'jam',
    status: 'shipped',
    event: 'NUGDS Winter Jam 2025 · 纽卡斯尔',
    award: '总分第一名，三项评分均为第一',
    role: '主程',
    team: '五人（NCU 计算机游戏工程同学）',
    tagline: '手持一台能穿越时空的相机，把过去拍进现在，解开房间深处的谜。',
    description: [
      '小巧的恐怖惊悚解谜游戏。相机拍下的历史物件会被带到当下，谜题就藏在两个时间的错位里。主题「shot」被我们同时解读成按下快门和扣动扳机。',
      '算是我正式参与制作的第一款游戏，团队由我和四名同学组成，本人任主程。当时啥都不懂，但最终做出来效果意外的不错。',
    ],
    cover: { kind: 'image', src: '/media/phantom-flash/shot-2.webp', alt: 'PhantomFlash：红光走廊里的人形模特' },
    gallery: [
      { kind: 'image', src: '/media/phantom-flash/shot-1.webp', alt: 'PhantomFlash：木屋走廊与手中的相机' },
      { kind: 'image', src: '/media/phantom-flash/shot-3.webp', alt: 'PhantomFlash：厨房里的取景框' },
      { kind: 'image', src: '/media/phantom-flash/award.webp', alt: 'itch.io 结果页：三项评分均为第一' },
    ],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1B0svHh5EHCS5sEoNHZNQZQ?pwd=mcn5', code: 'mcn5', label: '试玩包' },
    ],
    tags: ['Unity', 'C#', '3D'],
    featured: true,
  },
  {
    slug: 'ship-crash',
    title: '大船撞撞撞',
    year: '2026',
    kind: 'jam',
    status: 'shipped',
    event: 'CIGA Game Jam 2026 · 重庆站',
    role: '独立完成',
    team: '单人',
    tagline: '拖着锁链的海盗船互相冲撞。第一次把 AI 作画放进流程的一次实验。',
    description: [
      '单人 solo 的 jam 作品。第一次尝试 AI 作画，发现自己还不能很好地控制它，整体表现不及预期，玩法也堆得过于复杂。',
      '这些经验直接反哺到了《九宫地下城》：更克制的规则、更统一的美术语言。',
    ],
    cover: {
      kind: 'video',
      src: '/media/ship-crash/loop.mp4',
      poster: '/media/ship-crash/poster.webp',
      alt: '大船撞撞撞：两艘海盗船被锁链相连',
    },
    gallery: [],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1DVIws0T0JSjJphTm3Qfmmw?pwd=anwk', code: 'anwk', label: '试玩包' },
    ],
    tags: ['Unity', 'Solo'],
  },
  {
    slug: 'biodynamics',
    title: '生物动力学',
    year: '2026',
    kind: 'jam',
    status: 'shipped',
    event: '034 GameJam 2026',
    award: '从业者推荐奖（东极六感 田海博）',
    role: '独立完成',
    team: '单人 · 三天',
    tagline: '用弹性约束驱动一群小东西，看它们会不会涌现出好看的运动和好玩的规则。',
    description: [
      '三天的 solo 实验：把集群运动建在弹性约束上，看视觉和玩法能否从物理里自己长出来。结论是可控度不高，作为游戏算失败，但基础的视觉表现是成立的。',
      '意外拿到了评委的从业者推荐奖，奖项名叫「治疗孤独症与视力障碍的医学奇迹奖」。',
    ],
    cover: {
      kind: 'video',
      src: '/media/biodynamics/loop.mp4',
      poster: '/media/biodynamics/poster.webp',
      alt: '生物动力学：由弹性约束连接的彩色集群',
    },
    gallery: [{ kind: 'image', src: '/media/biodynamics/award.webp', alt: '034 挑战 GameJam 从业者推荐奖证书' }],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1TKxYdRtg0KBpMQzIo8Wh2A?pwd=4u7c', code: '4u7c', label: '试玩包' },
    ],
    tags: ['Unity', '物理', 'Solo'],
  },
  {
    slug: 'menbai',
    title: '面白',
    year: '2026',
    kind: 'jam',
    status: 'shipped',
    event: 'Global Game Jam 2026 · 成都站',
    award: '优秀奖（第三名）',
    role: 'TA / 副程',
    team: '五人（两美术、一策划、一 PM 兼主程）',
    tagline: '皮影戏风格的点击节奏游戏。你是本性纯善的精怪，却因世人误解沾染杀孽。',
    description: [
      '值此末世，常以真真假假是非曲直，纷扰人心。听闻有山鬼、虎姑、素仙三人，又听闻是一人。尝获「面白」一只，色若雪山，状若满月，有不老不死之用，难免欺人害命之名。',
      '我在队里做技术美术和部分程序。晚上在场地睡的时候空调坏了，差点冻死，所以这是拿命做的游戏（确信）。',
    ],
    cover: {
      kind: 'video',
      src: '/media/menbai/loop.mp4',
      poster: '/media/menbai/poster.webp',
      alt: '面白：皮影戏风格的角色在林间对峙',
    },
    gallery: [{ kind: 'image', src: '/media/menbai/jam-photo.webp', alt: 'GGJ 2026 成都站现场展示' }],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1FBsHkOItq3P2Pzmp0_aqiA?pwd=mq2i', code: 'mq2i', label: '试玩包' },
      { kind: 'video', url: 'https://www.bilibili.com/video/BV1u66tBcEkF/', label: '演示视频 · B站' },
    ],
    tags: ['Unity', 'Shader', '节奏'],
  },
  {
    slug: 'last-postman',
    title: '最后一名邮递员',
    latinTitle: 'The Last Postman',
    year: '2025',
    kind: 'jam',
    status: 'shipped',
    event: 'thatgamecompany 主题 Game Jam',
    role: '主程',
    team: '五人',
    tagline: '提着一盏会耗尽的煤油灯，在夜色里送最后一批信。',
    description: [
      '另一场 game jam 的作品，五人团队，我任主程。开发过程相当灾难，是一段痛苦的回忆，也是一段有用的回忆。',
    ],
    cover: { kind: 'image', src: '/media/last-postman/shot-2.webp', alt: '最后一名邮递员：夜色中提灯的邮递员' },
    gallery: [{ kind: 'image', src: '/media/last-postman/shot-1.webp', alt: '标题画面：灯塔' }],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1S8FFkXWlJA-bdBjz8vB2lg?pwd=m2kv', code: 'm2kv', label: '试玩包' },
    ],
    tags: ['Unity'],
  },
  {
    slug: 'helltel',
    title: '地狱酒店',
    latinTitle: 'Helltel',
    year: '2025',
    kind: 'jam',
    status: 'shipped',
    event: '吉比特游戏大赛',
    role: '主程 · 物理向 TA',
    team: '五人',
    tagline: '橡胶身体的服务员、神秘的粘液、诡异的住户。挑抹布之前，不考虑先来一根棒球棍吗？',
    description: [
      '一款酒店清洁模拟器，一切都非常奇怪。和 @邵年糕 以及其他三位队员合作，我负责程序和物理模拟方向的技术美术。',
      '角色是可控的软体，实现受到《章鱼奶爸》的启发。这套软体后来成了我研究生毕业论文的课题：软体物理动画在 Unity 中的稳定性优化。',
    ],
    cover: {
      kind: 'video',
      src: '/media/helltel/loop.mp4',
      poster: '/media/helltel/poster.webp',
      alt: '地狱酒店：橡胶身体的服务员在大堂里走动',
    },
    gallery: [
      {
        kind: 'video',
        src: '/media/helltel/loop-2.mp4',
        poster: '/media/helltel/poster.webp',
        alt: '地狱酒店：软体角色物理测试',
      },
    ],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1Ys1IjPFe6NVf_Mukfw-_wg?pwd=6y9c', code: '6y9c', label: '本体 + 宣传片' },
      { kind: 'video', url: 'https://youtu.be/CNH5Yst5X8M', label: '宣传片 · YouTube' },
    ],
    tags: ['Unity', '软体物理', 'TA'],
  },
  {
    slug: 'camera-summon',
    title: '相机召唤',
    year: '2025',
    kind: 'prototype',
    status: 'shelved',
    role: '独立完成',
    team: '单人',
    tagline: '拍下场景里的东西，再把它们召唤出来。一个 2D 玩法原型。',
    description: ['围绕「拍照即收集、召唤即使用」做的俯视角原型，验证相机作为核心动词能不能撑起一套关卡。'],
    cover: {
      kind: 'video',
      src: '/media/camera-summon/loop.mp4',
      poster: '/media/camera-summon/poster.webp',
      alt: '相机召唤原型：用取景框拍下物件后召唤到场景中',
    },
    gallery: [],
    links: [],
    tags: ['Unity', '原型'],
  },
  {
    slug: 'ncu-coursework',
    title: '渲染与物理小实验',
    latinTitle: 'C++ / OpenGL',
    year: '2024–25',
    kind: 'coursework',
    status: 'shipped',
    event: '纽卡斯尔大学 · 计算机游戏工程',
    role: '独立完成',
    team: '单人',
    tagline: '用 C++ 和 OpenGL 手搓的一组小项目：光照与材质、物理模拟。',
    description: [
      '研究生期间的一组课程项目，探索渲染和物理方面的技术。跑在一个自己做着玩的引擎上，魔改了很多包，算半自研。',
      '另外还有一个 C++/OpenGL 的俯视角 2D 小项目 demo，在 B 站有录像。',
    ],
    cover: {
      kind: 'video',
      src: '/media/ncu-coursework/loop.mp4',
      poster: '/media/ncu-coursework/poster.webp',
      alt: 'C++/OpenGL 物理课程作业演示',
    },
    gallery: [
      {
        kind: 'video',
        src: '/media/ncu-coursework/loop-2.mp4',
        poster: '/media/ncu-coursework/poster.webp',
        alt: 'C++/OpenGL 渲染课程作业演示',
      },
    ],
    links: [
      { kind: 'download', url: 'https://pan.baidu.com/s/1KVWZoZll2EQTekEWKxQJtA?pwd=ck6n', code: 'ck6n', label: '项目源码' },
      { kind: 'video', url: 'https://youtu.be/5zwIJxFsJh8', label: '演示 1 · YouTube' },
      { kind: 'video', url: 'https://youtu.be/ZecrZL8LVyg', label: '演示 2 · YouTube' },
      { kind: 'video', url: 'https://www.bilibili.com/video/BV1TBxkzmEQD/', label: '俯视角 2D demo · B站' },
    ],
    tags: ['C++', 'OpenGL', '渲染', '物理'],
  },
  {
    slug: 'itc',
    title: 'Infernal Transfer Company',
    latinTitle: 'Infernal Transfer Company',
    year: '—',
    kind: 'indie',
    status: 'shelved',
    role: '接手后的主程',
    team: '多人 · 远程',
    tagline: '接手一个停滞已久的项目，重排工作量，把 demo 推进过半；随后团队离散，项目搁置。',
    description: [
      '一个没能走到 demo 的项目，只留下几张图。我接手时它已经停滞了两年，重新规划工作量后把 demo 推进到一半，之后成员陆续离开，项目彻底停下。',
    ],
    cover: { kind: 'image', src: '/media/itc/shot-1.webp', alt: 'Infernal Transfer Company 概念实机图：西部矿镇' },
    gallery: [],
    links: [],
    tags: ['Unity', '未完成'],
  },
];

export const featuredProjects = projects.filter((p) => p.featured);

export const awardedProjects = projects.filter((p) => p.award);

export const projectBySlug = (slug: string) => projects.find((p) => p.slug === slug);
